# netlify.toml
[build]
  command = "next build && next export"
  publish = "out"

[[redirects]]
  from = "/docs/*"
  to = "https://lookup-guides.netlify.app/:splat"
  status = 200
  force = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
